### ISSUE TITLE
Best practices of Project Structure for .NET apps

### ISSUE THREAD

**Issue by iTKerry** [itkerry-mentorship/main#1]
**Description**:

The goal of this presentation is to show _best practices of Project Structure for .NET apps_. So we will talk about next things:

- [x] 1. Default way to create solution #2 
- [x] 2. What about Unit Tests? #4
- [x] 3. What about solution items? #5
- [x] 4. External files #6
- [x] 5. NuGet Packages #9
- [x] 6. How to deal with all of it? #7
- [x] 7. Conclusion #8

**Acceptable Criteria**:
- [x] Commit presentation into **github** folder of **main** repository (Commit [63c9474](https://github.com/itkerry-mentorship/main/commit/63c94743d58409c590b7f328556302193a5fd1f2))
